/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_v1_auth_get"];
        put?: never;
        /** Sign In */
        post: operations["sign_in_v1_auth_post"];
        /** Sign Out */
        delete: operations["sign_out_v1_auth_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description The loaded model. A list for backwards compatibility with 0.1.
         */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Model Catalog
         * @description Every model this server knows, including ones it cannot run here.
         */
        get: operations["model_catalog_v1_models_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Status */
        get: operations["model_status_v1_models_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Model
         * @description Replace the loaded model. Returns immediately; poll /v1/models/status.
         */
        post: operations["load_model_v1_models_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Providers
         * @description Remote catalogs this server can reach. Keys are never returned.
         */
        get: operations["list_providers_v1_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/{provider_id}/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Provider Key
         * @description Store a provider credential server-side. It is never sent back.
         */
        put: operations["set_provider_key_v1_providers__provider_id__key_put"];
        post?: never;
        /** Clear Provider Key */
        delete: operations["clear_provider_key_v1_providers__provider_id__key_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/{provider_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Provider Models
         * @description Search a provider's catalog.
         *
         *     The default filter is the point of the whole tab: of the hundreds of models
         *     OpenRouter lists, only the ones that actually output an image can generate
         *     one here.
         */
        get: operations["list_provider_models_v1_providers__provider_id__models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/pinned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pinned
         * @description The remote models kept on this platform, usable from the compose form.
         */
        get: operations["list_pinned_v1_providers_pinned_get"];
        put?: never;
        post?: never;
        /** Unpin Model */
        delete: operations["unpin_model_v1_providers_pinned_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/{provider_id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pin Model */
        post: operations["pin_model_v1_providers__provider_id__pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Gpus */
        get: operations["list_gpus_v1_gpus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Generation
         * @description Text to image. Returns a job id; poll /v1/jobs/{id} for the result.
         */
        post: operations["create_generation_v1_images_generations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images/edits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Edit
         * @description Edit or combine 1..N reference images supplied as base64/data URIs.
         */
        post: operations["create_edit_v1_images_edits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images/edits/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Edit Upload
         * @description Same as /v1/images/edits but with multipart file uploads.
         */
        post: operations["create_edit_upload_v1_images_edits_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description The archive, newest first, scoped to the key that made the work.
         */
        get: operations["list_jobs_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Job
         * @description Remove one job from the archive, and the files it produced.
         */
        delete: operations["delete_job_v1_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Image
         * @description Raw bytes of one produced image, handy for `curl -o out.png`.
         */
        get: operations["get_job_image_v1_jobs__job_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/files/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File */
        get: operations["get_file_v1_files__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_edit_upload_v1_images_edits_upload_post */
        Body_create_edit_upload_v1_images_edits_upload_post: {
            /** Prompt */
            prompt: string;
            /** Images */
            images: string[];
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Num Steps */
            num_steps?: number | null;
            /** Guidance */
            guidance?: number | null;
            /** Seed */
            seed?: number | null;
            /**
             * Num Images
             * @default 1
             */
            num_images: number;
            /** @default none */
            upsample_prompt: components["schemas"]["UpsampleMode"];
            /** Match Image Size */
            match_image_size?: number | null;
            /**
             * Response Format
             * @default b64_json
             */
            response_format: string;
        };
        /**
         * CatalogEntry
         * @description One model this server knows about, runnable here or not.
         */
        CatalogEntry: {
            /** Id */
            id: string;
            /** Repo Id */
            repo_id: string;
            /** Family */
            family: string;
            /** Label */
            label: string;
            /** Summary */
            summary: string;
            /** Licence */
            licence: string;
            /** Licence Url */
            licence_url: string;
            /** Commercial Use */
            commercial_use: boolean;
            /** Capabilities */
            capabilities: ("text-to-image" | "image-edit" | "multi-reference")[];
            /** Default Steps */
            default_steps: number;
            /** Default Guidance */
            default_guidance: number;
            /** Step Range */
            step_range: number[];
            /** Guidance Range */
            guidance_range: number[];
            /** Precision */
            precision: string;
            /** Transformer Vram Gb */
            transformer_vram_gb: number;
            /** Text Encoder Vram Gb */
            text_encoder_vram_gb: number;
            /** Total Vram Gb */
            total_vram_gb: number;
            /** Gated */
            gated: boolean;
            /** Notes */
            notes: string;
            /** Custom */
            custom: boolean;
            /** Loaded */
            loaded: boolean;
            /**
             * Placement
             * @enum {string}
             */
            placement: "split" | "single" | "offload" | "none";
            /** Placement Reason */
            placement_reason: string;
            /** Runnable */
            runnable: boolean;
            /** Max Pixels */
            max_pixels: number;
        };
        /**
         * EditRequest
         * @description POST /v1/images/edits (JSON variant).
         *
         *     `images` accepts base64 payloads or data URIs. FLUX.2 conditions on the
         *     VAE-encoded references appended to the image token sequence, so several
         *     references can be combined in one call.
         */
        EditRequest: {
            /** Prompt */
            prompt: string;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Num Steps */
            num_steps?: number | null;
            /** Guidance */
            guidance?: number | null;
            /** Seed */
            seed?: number | null;
            /**
             * Num Images
             * @default 1
             */
            num_images: number;
            /** @default none */
            upsample_prompt: components["schemas"]["UpsampleMode"];
            /** Upsample Model */
            upsample_model?: string | null;
            /** Model */
            model?: string | null;
            /** @default b64_json */
            response_format: components["schemas"]["ResponseFormat"];
            /** @default png */
            output_format: components["schemas"]["OutputFormat"];
            /** Images */
            images: string[];
            /**
             * Match Image Size
             * @description Index of the reference image whose dimensions the output should copy.
             */
            match_image_size?: number | null;
        };
        /**
         * GenerationRequest
         * @description POST /v1/images/generations
         */
        GenerationRequest: {
            /** Prompt */
            prompt: string;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Num Steps */
            num_steps?: number | null;
            /** Guidance */
            guidance?: number | null;
            /** Seed */
            seed?: number | null;
            /**
             * Num Images
             * @default 1
             */
            num_images: number;
            /** @default none */
            upsample_prompt: components["schemas"]["UpsampleMode"];
            /** Upsample Model */
            upsample_model?: string | null;
            /** Model */
            model?: string | null;
            /** @default b64_json */
            response_format: components["schemas"]["ResponseFormat"];
            /** @default png */
            output_format: components["schemas"]["OutputFormat"];
        };
        /** GenerationResponse */
        GenerationResponse: {
            /** Id */
            id: string;
            /** Model */
            model: string;
            /** Created */
            created: number;
            /** Prompt */
            prompt: string;
            /** Revised Prompt */
            revised_prompt?: string | null;
            /** Images */
            images: components["schemas"]["ImagePayload"][];
            /** Timings */
            timings: {
                [key: string]: number;
            };
        };
        /** GpuInfo */
        GpuInfo: {
            /** Index */
            index: number;
            /** Name */
            name: string;
            /** Memory Total Mb */
            memory_total_mb: number;
            /** Memory Used Mb */
            memory_used_mb: number;
            /** Role */
            role?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "loading" | "error" | "switching";
            /** Model Loaded */
            model_loaded: boolean;
            model: components["schemas"]["ModelStatusResponse"];
            /** Queue Depth */
            queue_depth: number;
            /** Queue Active */
            queue_active: number;
            /** Queue Paused */
            queue_paused: boolean;
            /** Auth Required */
            auth_required: boolean;
            /** Gpus */
            gpus: components["schemas"]["GpuInfo"][];
            storage: components["schemas"]["StorageInfo"];
            /** Detail */
            detail?: string | null;
        };
        /** ImagePayload */
        ImagePayload: {
            /** B64 Json */
            b64_json?: string | null;
            /** Url */
            url?: string | null;
            /** Seed */
            seed: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /**
         * JobImage
         * @description A produced file as the archive refers to it.
         */
        JobImage: {
            /** Url */
            url?: string | null;
            /** Seed */
            seed: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * Available
             * @default true
             */
            available: boolean;
        };
        /**
         * JobPage
         * @description A window onto the archive, with the total so the UI can page honestly.
         */
        JobPage: {
            /** Jobs */
            jobs: components["schemas"]["JobSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * JobRequest
         * @description What was asked for, independent of what came back.
         *
         *     A refused or failed job has no result, and that is exactly when the
         *     operator most needs the settings back to adjust and try again.
         */
        JobRequest: {
            /** Prompt */
            prompt: string;
            /**
             * Kind
             * @default generation
             */
            kind: string;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Num Steps */
            num_steps?: number | null;
            /** Guidance */
            guidance?: number | null;
            /** Seed */
            seed?: number | null;
            /**
             * Num Images
             * @default 1
             */
            num_images: number;
            /** Upsample Mode */
            upsample_mode?: string | null;
            /** Upsample Model */
            upsample_model?: string | null;
            /** Model Id */
            model_id?: string | null;
            /** Model Label */
            model_label?: string | null;
            /**
             * Remote
             * @default false
             */
            remote: boolean;
            /**
             * Reference Count
             * @default 0
             */
            reference_count: number;
            /** References */
            references?: components["schemas"]["JobImage"][];
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "queued" | "running" | "succeeded" | "failed" | "rejected";
        /** JobStatusResponse */
        JobStatusResponse: {
            /** Id */
            id: string;
            status: components["schemas"]["JobState"];
            /** Created */
            created: number;
            /** Started */
            started?: number | null;
            /** Finished */
            finished?: number | null;
            /** Queue Position */
            queue_position?: number | null;
            /** Progress */
            progress?: number | null;
            request?: components["schemas"]["JobRequest"] | null;
            result?: components["schemas"]["GenerationResponse"] | null;
            /** Error */
            error?: string | null;
        };
        /** JobSubmitted */
        JobSubmitted: {
            /** Id */
            id: string;
            status: components["schemas"]["JobState"];
            /** Queue Position */
            queue_position: number;
            /** Poll Url */
            poll_url: string;
        };
        /**
         * JobSummary
         * @description One row of GET /v1/jobs.
         *
         *     Carries everything a gallery cell renders — prompt, size, seed, model and
         *     the image URLs — because a grid of hundreds of rows cannot afford a
         *     follow-up request per cell.
         */
        JobSummary: {
            /** Id */
            id: string;
            status: components["schemas"]["JobState"];
            /** Kind */
            kind: string;
            /** Created */
            created: number;
            /** Started */
            started?: number | null;
            /** Finished */
            finished?: number | null;
            /** Progress */
            progress?: number | null;
            /** Prompt */
            prompt: string;
            /** Revised Prompt */
            revised_prompt?: string | null;
            /** Model Id */
            model_id?: string | null;
            /** Model Label */
            model_label?: string | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Num Steps */
            num_steps?: number | null;
            /** Guidance */
            guidance?: number | null;
            /** Seed */
            seed?: number | null;
            /**
             * Num Images
             * @default 1
             */
            num_images: number;
            /** Upsample Mode */
            upsample_mode?: string | null;
            /**
             * Reference Count
             * @default 0
             */
            reference_count: number;
            /** Queue Position */
            queue_position?: number | null;
            /** Duration S */
            duration_s?: number | null;
            /** Images */
            images?: components["schemas"]["JobImage"][];
            /**
             * Image Count
             * @default 0
             */
            image_count: number;
            /** Error */
            error?: string | null;
        };
        /**
         * ModelInfo
         * @description The model that is loaded right now, and how it sits on the hardware.
         */
        ModelInfo: {
            /** Id */
            id: string;
            /** Repo Id */
            repo_id: string;
            /** Family */
            family: string;
            /** Label */
            label: string;
            /** Licence */
            licence: string;
            /** Licence Url */
            licence_url: string;
            /** Commercial Use */
            commercial_use: boolean;
            /**
             * Placement
             * @enum {string}
             */
            placement: "split" | "single" | "offload" | "none";
            /** Placement Reason */
            placement_reason: string;
            /** Transformer Device */
            transformer_device: string;
            /** Text Encoder Device */
            text_encoder_device: string;
            /** Cpu Offload */
            cpu_offload: boolean;
            /** Precision */
            precision: string;
            /** Max Pixels */
            max_pixels: number;
            /** Capabilities */
            capabilities: ("text-to-image" | "image-edit" | "multi-reference")[];
            /** Supports Local Upsample */
            supports_local_upsample: boolean;
            /** Step Range */
            step_range: number[];
            /** Guidance Range */
            guidance_range: number[];
            /** Max Reference Images */
            max_reference_images: number;
            /** Defaults */
            defaults: {
                [key: string]: number;
            };
        };
        /**
         * ModelStatusResponse
         * @description Where a load or a swap has got to.
         */
        ModelStatusResponse: {
            /**
             * State
             * @enum {string}
             */
            state: "loading" | "ready" | "switching" | "error";
            /** Model Id */
            model_id?: string | null;
            /** Target Id */
            target_id?: string | null;
            /** Phase */
            phase: string;
            /** Progress */
            progress: number;
            /** Detail */
            detail?: string | null;
            /** Started */
            started: number;
            /** Finished */
            finished?: number | null;
        };
        /** ModelSwitchRequest */
        ModelSwitchRequest: {
            /**
             * Model
             * @description A catalog id (e.g. 'flux1-schnell') or a huggingface repo id.
             */
            model: string;
        };
        /**
         * OutputFormat
         * @enum {string}
         */
        OutputFormat: "png" | "jpeg" | "webp";
        /** PinRequest */
        PinRequest: {
            /** Model Id */
            model_id: string;
        };
        /** PinnedModelInfo */
        PinnedModelInfo: {
            /** Key */
            key: string;
            /** Provider */
            provider: string;
            /** Model Id */
            model_id: string;
            /** Label */
            label: string;
            /** Makes Images */
            makes_images: boolean;
            /** Reads Images */
            reads_images: boolean;
            /** Price Image */
            price_image?: string | null;
        };
        /** ProviderInfoResponse */
        ProviderInfoResponse: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Summary */
            summary: string;
            /** Docs Url */
            docs_url: string;
            /** Key Url */
            key_url: string;
            /** Supports Generation */
            supports_generation: boolean;
            /** Configured */
            configured: boolean;
            /**
             * Key Source
             * @enum {string}
             */
            key_source: "none" | "env" | "stored";
            /** Catalog Is Public */
            catalog_is_public: boolean;
        };
        /** ProviderKeyRequest */
        ProviderKeyRequest: {
            /** Key */
            key: string;
        };
        /** RemoteModelInfo */
        RemoteModelInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Input Modalities */
            input_modalities: string[];
            /** Output Modalities */
            output_modalities: string[];
            /** Context Length */
            context_length?: number | null;
            /** Price Image */
            price_image?: string | null;
            /** Price Prompt */
            price_prompt?: string | null;
            /** Is Router */
            is_router: boolean;
            /** Makes Images */
            makes_images: boolean;
            /** Reads Images */
            reads_images: boolean;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
        };
        /** RemoteModelPage */
        RemoteModelPage: {
            /** Models */
            models: components["schemas"]["RemoteModelInfo"][];
            /** Total */
            total: number;
            /** Catalog Total */
            catalog_total: number;
        };
        /**
         * ResponseFormat
         * @enum {string}
         */
        ResponseFormat: "b64_json" | "url";
        /** StorageInfo */
        StorageInfo: {
            /** Used Bytes */
            used_bytes: number;
            /** File Count */
            file_count: number;
            /** Max Bytes */
            max_bytes?: number | null;
            /** Max Age Days */
            max_age_days?: number | null;
        };
        /**
         * UpsampleMode
         * @enum {string}
         */
        UpsampleMode: "none" | "local" | "openrouter";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    whoami_v1_auth_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_in_v1_auth_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_out_v1_auth_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"][];
                };
            };
        };
    };
    model_catalog_v1_models_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogEntry"][];
                };
            };
        };
    };
    model_status_v1_models_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStatusResponse"];
                };
            };
        };
    };
    load_model_v1_models_load_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelSwitchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_v1_providers_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderInfoResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_provider_key_v1_providers__provider_id__key_put: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                provider_id: string;
            };
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_provider_key_v1_providers__provider_id__key_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                provider_id: string;
            };
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_provider_models_v1_providers__provider_id__models_get: {
        parameters: {
            query?: {
                /** @description Substring of the id, name or description */
                q?: string;
                /** @description 'image' keeps only models that output images */
                kind?: string;
                limit?: number;
                include_routers?: boolean;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                provider_id: string;
            };
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemoteModelPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pinned_v1_providers_pinned_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinnedModelInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpin_model_v1_providers_pinned_delete: {
        parameters: {
            query: {
                /** @description provider:model_id */
                key: string;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pin_model_v1_providers__provider_id__pin_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                provider_id: string;
            };
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinnedModelInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gpus_v1_gpus_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GpuInfo"][];
                };
            };
        };
    };
    create_generation_v1_images_generations_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSubmitted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_edit_v1_images_edits_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSubmitted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_edit_upload_v1_images_edits_upload_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_edit_upload_v1_images_edits_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSubmitted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Filter by job status */
                status?: components["schemas"]["JobState"] | null;
                /** @description 'generation' or 'edit' */
                kind?: string | null;
                model_id?: string | null;
                /** @description Substring of the prompt */
                search?: string | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: {
                /** @description Seconds to block waiting */
                wait?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_v1_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_image_v1_jobs__job_id__image_get: {
        parameters: {
            query?: {
                index?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_v1_files__name__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: {
                oig_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
